slogans :tuple[str] = (
"Just Do It",
"I’m Lovin’ It",
"Think Different",
"Because You’re Worth It",
"Got Milk?",
"Eat Fresh",
"The Happiest Place On Earth",
"America Runs on Dunkin",
"Finger Lickin’ GoodKFC",
"There Are Some Things Money Can’t Buy. For Everything Else, There’s MasterCard",
"The Ultimate Driving Machine",
"Betcha Can’t Eat Just One",
"A Diamond Is Forever",
"Have It Your Way",
"Snap! Crackle! Pop!",
"Taste the Rainbow",
"The King of Beers",
"Can You Hear Me Now? Good.",
"Melts in Your Mouth, Not in Your Hands",
"It Gives You Wings",
"Think Small",
"We Try Harder",
"Don’t Leave Home Without It",
"The Quicker Picker Upper",
"When It Rains, It Pours",
"Let’s Go Places",
"Breakfast of Champions",
"What Happens Here, Stays Here",
"Imagination at Work",
"Save Money. Live Better.",
"Every Little Helps",
"Open Happiness",
"Keep Going",
"Impossible is Nothing",
"The Relentless Pursuit of Perfection",
"Connecting People",
"I Am What I Am",
"Good to the Last Drop",
"The World’s Local Bank",
"Share Moments. Share Life.",
"Fly the Friendly Skies",
"The Real Thing",
"It’s Everywhere You Want to Be",
"Hello Moto",
"Like a Good Neighbor, State Farm is There",
"Have a Break, Have a Kit Kat",
"Quality Never Goes Out of Style",
"There’s No Substitute for Quality",
"Ideas for Life",
"Challenge Everything",
"Reach Out and Touch Someone",
"Be All You Can Be",
"Think Outside the Bun",
"When You Care Enough to Send the Very Best",
"Better Ingredients. Better Pizza.",
"Driven by Passion",
"Look Sharp, Feel Sharp",
"Make the Most of Now",
"Life’s Good",
"Share the Fantasy",
"Play. Laugh. Grow.",
"Go Further",
"The Power of Dreams",
"Don’t Crack Under Pressure",
"Do More",
"Expect More. Pay Less.",
"Designed for Driving Pleasure",
"You’re in Good Hands",
"Taste So Good, Cats Ask for It by Name",
"Because Change Happens",
"Plop, Plop, Fizz, Fizz, Oh What a Relief It Is",
"Stronger than Dirt",
"Is It In You?",
"Easy, Breezy, Beautiful",
"Solutions for a Small Planet",
"Don’t Just Book It, Thomas Cook It",
"The Few. The Proud. The Marines.",
"Let Your Fingers Do the Walking",
"It Takes a Licking and Keeps on Ticking",
"The Best a Man Can Get",
"Once You Pop, You Can’t Stop",
"See the USA in Your Chevrolet",
"The Best Part of Waking Up is Folgers in Your Cup",
"They’re G-r-r-reat!",
"Live in Your World, Play in Ours",
"Where’s the Beef?",
"Have More Fun",
"What’s in Your Wallet?",
"The World on Time",
"Be More Dog",
"Refresh Everything",
"Belong Anywhere",
"Every Kiss Begins with Kay",
"Moving Forward",
"That Was Easy",
"High Performance, Delivered",
"The Original. If Your Grandfather Hadn’t Worn It, You Wouldn’t Exist",
"Do What You Can’t",
"Move the Way You Want",
"Rewards Reimagined",
"Let Us Guide You Home""Got Milk?",
"Every Little Helps.",
"Melts in Your Mouth, Not in Your Hands.",
"The Quicker Picker Upper.",
"A Diamond is Forever.",
"Betcha Can’t Eat Just One.",
"Advancement Through Technology.",
"America Runs on Dunkin.",
"I’m Lovin’ It.",
"Imagination at Work.",
"Can You Hear Me Now? Good.",
"Because You’re Worth It.",
"It Could be You.",
"The miracles of Science.",
"Buy it. Sell it. Love it.",
"The Last Place You Want To Go.",
"Get N or Get Out.",
"You have met Life Today?",
"Be Stupid.",
"Fly The Friendly Sky.",
"Grace, Space, pace.",
"Melt in your Mouth not in your Hands.",
"It’s Everywhere u want to be.",
"Have it your Way.",
"Good to the last Drop.",
"Make the most no Now.",
"Your Vision our Future.",
"Challenge Everything.",
"Eat Fresh.",
"Make Believe.",
"Success. It’s a Mind Game.",
"Connecting People.",
"Quality Never Goes out Of Style.",
"Share Moments. Share Life.",
"Because life’s Complected enough.",
"Stronger than dirt.",
"Pleasing people over the World.",
"There is no Substitute.",
"At the heart of image.",
"Innovation.",
"See what we Mean.",
"Push button Publishing.",
"Think Small.",
"Make it matter",
"Think IBM",
"Making it all make sense",
"Don’t be evil",
"Sponsors of tomorrow",
"Let’s Live Life Better",
"Keeping an eye on things",
"Your Trusted Security Company",
"The professional approach to security",
"Safe, Secure, Service",
"Trust us with your business, We will guard you with ours",
"Your safety is our first priority",
"You’re in good hands",
"Redefining standards",
"Transform tomorrow",
"We’ve got you under our wing",
"Insurance solutions from A to Z",
"Enriching the lives of people, we touch",
"The relationship company"
)